// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/about.tsx";
import * as $3 from "./routes/github/[username].tsx";
import * as $4 from "./routes/github/_middleware.ts";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/search.tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/about.tsx": $2,
    "./routes/github/[username].tsx": $3,
    "./routes/github/_middleware.ts": $4,
    "./routes/index.tsx": $5,
    "./routes/search.tsx": $6,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
